/**
 * 把 dom2pdf-wasm 的 .wasm 二进制读取后转成 base64，
 * 生成 src/wasm-base64.ts，供 wasm-glue.ts 内联使用。
 *
 * 这样打包后的 JS 库不依赖外部 .wasm 文件，单文件即可分发。
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
// 优先用 workspace 软链路径，不存在时回退到 monorepo 根的兄弟包目录。
let wasmPath = resolve(__dirname, '../node_modules/dom2pdf-wasm/pkg/dom2pdf_wasm.wasm');
if (!existsSync(wasmPath)) {
  wasmPath = resolve(__dirname, '../../dom2pdf-wasm/pkg/dom2pdf_wasm.wasm');
}
const outPath = resolve(__dirname, '../src/wasm-base64.ts');

const bytes = readFileSync(wasmPath);
const b64 = bytes.toString('base64');
const sizeKb = (bytes.length / 1024).toFixed(1);

const ts = `// AUTO-GENERATED by scripts/inline-wasm.mjs — do not edit.
// Source: dom2pdf-wasm/pkg/dom2pdf_wasm.wasm (${sizeKb} KB, ${bytes.length} bytes)
// Inlined as base64 so the published JS lib is a single file (no fetch needed).

export const WASM_BASE64 =
  '${b64}';

export const WASM_BYTE_LENGTH = ${bytes.length};
`;

writeFileSync(outPath, ts);
console.log(`[inline-wasm] wrote ${outPath} (${sizeKb} KB wasm -> ${b64.length} chars base64)`);
